apiVersion: batch/v1beta1
kind: CronJob
metadata: 
  name: demo-CronJob
spec:
  schedule: "*/1 * * * *"
  jobTemplate: 
    spec:
      template:
        spec:
          containers:
            - name: demo-CronJob-minfy
              image: busybox
              args: 
              - /bin/sh
              - c 
              - date; echo hi rakshith how are you 
          restartPolicy: OnFailure
