apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: rakshith
  labels: 
    env: test
spec: 
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec: 
      containers:
      - name: rakshith
        image: nginx
        ports:
        - containerPort: 80